-- MySQL Script generated by MySQL Workbench
-- Wed Aug  3 16:12:50 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema livranet
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `livranet` ;

-- -----------------------------------------------------
-- Schema livranet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `livranet` DEFAULT CHARACTER SET utf8 ;
USE `livranet` ;

-- -----------------------------------------------------
-- Table `livranet`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livranet`.`Usuario` (
  `codigo_usuario` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `nome_usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `livranet`.`Livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `livranet`.`Livro` (
  `codigo_livro` INT NOT NULL AUTO_INCREMENT,
  `autor` VARCHAR(45) NOT NULL,
  `ano_de_lancamento` CHAR(4) NOT NULL,
  `nome_do_livro` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo_livro`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
